---
- hosts: vms
  become: yes
  tasks:
    - name: Add Docker GPG APT key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
       name: docker-ce
       state: latest

    - name: Pull Docker image
      docker_image:
        name: your-dockerhub-username/your-python-app
        tag: "{{ jenkins_build_number }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: python_app
        image: your-dockerhub-username/your-python-app:{{ jenkins_build_number }}
        state: started
        ports:
          - "5000:5000"
        restart_policy: always
